### ISSUE TITLE
Why would vgic_dist_reset function in dornerworks/seL4_projects_libs cause an data exception?

### ISSUE THREAD

**Issue by chengshuyi** [dornerworks/sel4-armv8-vmm-manifest#2]
Here is the problematic [code link](https://github.com/dornerworks/seL4_projects_libs/blob/b79f6d1a62a2396ae74b21af08d4bd3b2c2fb75c/libsel4arm-vmm/src/arch/arm/devices/vgic/vgic500.c#L945]).

```
    gic_dist->typer            = 0x7B04B0; /* RO */
    gic_dist->iidr             = 0x1043B ; /* RO */
```

I have checked the asm code. The disassembly is:

```
mov   x4, #0x4b0
movk x4, #0x7b, lsl #16
movk x4, #0x43b, lsl #32
movk x4, #0x1, lsl #48
stur x4, [x3,#4]                                       //here is the exception instruction.
```

As we can see, the compiler pack *typer* and *iidr* and use *stur* instruction to store it to memory.

I am confused *vgic_dist_reset* function would run correctly, if i commented the two line code.

Thanks for any advice!

**Comment by lydmcu** [comment]
hi,
   I meet the same problem, do you find the reason? Thank you very much.

**Comment by chengshuyi** [comment]
> hi,
> I meet the same problem, do you find the reason? Thank you very much.

Yes, see this [comment](https://github.com/dornerworks/sel4-armv8-vmm-manifest/issues/3#issuecomment-544465411) . The compiler have optimised the code and combine two 32 bit number into one 64bit number which have the probability to cause data abort, alignment fault. 

The solve is to disable optimisation.

**Comment by lydmcu** [comment]
hi，
I am sorry to bother you again.
now, I can see my vm linux begin to start. but it failed when mount ramdisk on /dev/ram
I just fount the project add Image1 and dtb, 
how can I add my ramdisk in the project ? can you give me some advice?
                                                                thank you very much!

**Comment by chengshuyi** [comment]
> hi，
> I am sorry to bother you again.
> now, I can see my vm linux begin to start. but it failed when mount ramdisk on /dev/ram
> I just fount the project add Image1 and dtb,
> how can I add my ramdisk in the project ? can you give me some advice?
> thank you very much!

you can open a new issue and post the boot log.

**Comment by lydmcu** [comment]
hi,
I put the issue below list, can you give me some advice, thank you very much.
https://github.com/dornerworks/sel4-armv8-vmm-manifest/issues/4
